blueprint:
  name: Random-Light-Activation
  description: Random light activation
  domain: automation
  author: Rob Maskell
  input:
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: time
    at: 
      data_template: "21:0{{ range(3,9) | random }}:00"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
